name: Prepare deploy
description: Prepare deploy to Lambda

runs:
    using: "composite"
    steps:
        -   name: Setup PHP
            uses: shivammathur/setup-php@v2
            with:
                php-version: 8.1
                extensions: apcu, redis
                coverage: none

        -   name: Setup Node
            uses: actions/setup-node@v2
            with:
                node-version: 16

        -   name: Download dependencies
            uses: ramsey/composer-install@v2
            with:
                composer-options: "--no-dev --no-scripts"

        -   name: Yarn install
            shell: bash
            run: yarn install --frozen-lockfile

        -   name: Install assets
            shell: bash
            run: bin/console assets:install public --env=prod

        -   name: Warmup cache
            shell: bash
            run: |
                rm -rf var/cache/*
                bin/console cache:warmup --env=prod
                echo "<?php return ['GIT_SHA1'=>'`git rev-parse --short HEAD`'];" > .env.local.php
                cat .env.local.php
